// <auto-generated />
namespace ProjectAriel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addPropertiesToCardModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPropertiesToCardModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201409070014172_addPropertiesToCardModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
